# Generated by Django 2.2.13 on 2020-07-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content_de',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_tr',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug_de',
            field=models.SlugField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug_en',
            field=models.SlugField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug_tr',
            field=models.SlugField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_de',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_tr',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
