# Generated by Django 2.2.13 on 2020-07-31 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200731_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content_de',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content_tr',
        ),
    ]
