# Generated by Django 2.2.13 on 2020-07-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0003_auto_20200730_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='slug',
            field=models.SlugField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='slug_de',
            field=models.SlugField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='home',
            name='slug_en',
            field=models.SlugField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='home',
            name='slug_tr',
            field=models.SlugField(max_length=30, null=True, unique=True),
        ),
    ]
